[package]
name = "stylist-macros"
version = "0.12.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
stylist-core = { path = "../stylist-core", version = "0.12", features = ["parser"] }

litrs = "0.4.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.47"
quote = "1.0.21"
nom = "7.1.1"
syn = { version = "1.0.105", features = ["full", "extra-traits"] }
itertools = "0.10.5"
log = "0.4.17"